# Generated by Django 4.1.5 on 2023-01-31 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Size',
            field=models.CharField(max_length=50),
        ),
    ]
